task:
  name: "Build"
  timeout_in: 600m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
 env:
    MANIFEST: https://github.com/PixelExperience/manifest.git -b eleven-plus
    DEVICE: miatoll
    OEM: xiaomi
    DT_LINK: https://github.com/PixelExperience-Devices/device_xiaomi_miatoll.git
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_miatoll.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/ArrowOS-Devices/android_kernel_xiaomi_sm6250.git
    PLATFORM: sm6250
    KT_PATH: kernel/$OEM/$PLATFORM
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: aosp_${DEVICE}-userdebug
    OUTPUT: PixelExperience*.zip
 
 

 echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init -u $MANIFEST
      - repo sync -j31 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $KT_LINK $KT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  build_script:
    - source build/envsetup.sh
    - lunch aosp_holi-userdebug
    - m bacon -j$(nproc --all)
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }

    up out/target/product/holi/*.zip
    up out/target/product/holi/boot.img
