task:
  name: "Build"
  timeout_in: 600m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  clone_script:
    - repo init -u https://github.com/PixelExperience/manifest -b thirteen || true
  sync_script:
    - rm -rf .repo/local_manifests || true
    - git clone https://github.com/rombuilder/local_manifest.git --depth 1 -b main .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
    - rm -rf hardware/qcom-caf/sm8350
  build_script:
    - source build/envsetup.sh
    - lunch aosp_holi-userdebug
    - m bacon -j$(nproc --all)
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }

    up out/target/product/holi/*.zip
    up out/target/product/holi/boot.img
